version: "2.2"
services:
  postgres:
    image: "postgres:12.1"
  api:
#    network_mode: host
    environment:
      - DB_HOST=postgres
    env_file:
      - .env
    build: "."
    volumes:
      - ./src:/usr/src/self_tracker/src
    ports:
      - 8090:8090
